### PR TITLE
randbp: Use a global rander instead of side effect

### PR DESCRIPTION
**Pull request by fishy**
Instead of relying on side effect to proper seed math/rand, use a global
rander randbp.R. This way it's more obvious to tell in code which are
properly seeded and which are not.

### CODE REVIEW

**Comment by konradreiche** [comment]
So is it that this way we provide an already-seeded random generator and it comes with thread-safe access? Should this become the canonical way to access random numbers in baseplate.go or is this more a utility package?

**Comment by fishy** [comment]
> So is it that this way we provide an already-seeded random generator and it comes with thread-safe access? Should this become the canonical way to access random numbers in baseplate.go or is this more a utility package?

Yes this is supposed to be the canonical way when you want to use the global functions inside `math/rand`, except `Read`. I'll update the comment to be more clear.

**Comment by fishy** [comment]
:haircut:

I did a different approach for Read, now instead of always ~20x performance hit, it has a constant ~2us overhead for small buffers. New benchmark result:

```
$ go test -bench Rand -benchmem
goos: darwin
goarch: amd64
pkg: github.com/reddit/baseplate.go/randbp
BenchmarkRand/Read/size-16/math/rand-8         	 8561205	       135 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-16/crypto/rand-8       	 9864148	       121 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-16/randbp-8            	  616458	      2188 ns/op	    5376 B/op	       1 allocs/op
BenchmarkRand/Read/size-64/math/rand-8         	 5410232	       226 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-64/crypto/rand-8       	 6034893	       197 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-64/randbp-8            	  585349	      2292 ns/op	    5376 B/op	       1 allocs/op
BenchmarkRand/Read/size-256/math/rand-8        	 4339696	       276 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-256/crypto/rand-8      	 2262680	       527 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-256/randbp-8           	  552925	      2665 ns/op	    5376 B/op	       1 allocs/op
BenchmarkRand/Read/size-512/math/rand-8        	 2498294	       481 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-512/crypto/rand-8      	 1000000	      1007 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-512/randbp-8           	  562596	      3068 ns/op	    5376 B/op	       1 allocs/op
BenchmarkRand/Read/size-1024/math/rand-8       	 1215046	       925 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-1024/crypto/rand-8     	  615151	      1965 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-1024/randbp-8          	  366847	      3326 ns/op	    5376 B/op	       1 allocs/op
BenchmarkRand/Read/size-4096/math/rand-8       	  310474	      3762 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-4096/crypto/rand-8     	  160294	      7593 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-4096/randbp-8          	  363007	      3891 ns/op	    5376 B/op	       1 allocs/op
BenchmarkRand/Read/size-1048576/math/rand-8    	    1334	    859627 ns/op	    6291 B/op	       0 allocs/op
BenchmarkRand/Read/size-1048576/crypto/rand-8  	     873	   1346834 ns/op	    9610 B/op	       0 allocs/op
BenchmarkRand/Read/size-1048576/randbp-8       	    5290	    248981 ns/op	    6963 B/op	       1 allocs/op
BenchmarkRand/Uint64/math/rand-8               	11521963	       104 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Uint64/randbp-8                  	11381798	       120 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Float64/math/rand-8              	13106461	        95.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Float64/randbp-8                 	12249634	       112 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/NormFloat64/math/rand-8          	 9724162	       125 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/NormFloat64/randbp-8             	 9555594	       137 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/ExpFloat64/math/rand-8           	10369075	       118 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/ExpFloat64/randbp-8              	11349109	       125 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Shuffle/size-16/math/rand-8      	  794672	      2019 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-16/randbp-8         	  741896	      1914 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-64/math/rand-8      	  181123	      7991 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-64/randbp-8         	  161839	      7934 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-256/math/rand-8     	   35317	     32076 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-256/randbp-8        	   43243	     29001 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-512/math/rand-8     	   20580	     63401 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-512/randbp-8        	   19988	     67990 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-1024/math/rand-8    	   10000	    127742 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-1024/randbp-8       	   10000	    133007 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-4096/math/rand-8    	    2014	    500121 ns/op	      34 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-4096/randbp-8       	    2478	    479611 ns/op	      33 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-1048576/math/rand-8 	      63	 135440432 ns/op	   16684 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-1048576/randbp-8    	      60	 134214104 ns/op	   17523 B/op	       1 allocs/op
BenchmarkRand/Perm/size-16/math/rand-8         	  718550	      1971 ns/op	     128 B/op	       1 allocs/op
BenchmarkRand/Perm/size-16/randbp-8            	  614610	      1991 ns/op	     128 B/op	       1 allocs/op
BenchmarkRand/Perm/size-64/math/rand-8         	  177740	      7485 ns/op	     512 B/op	       1 allocs/op
BenchmarkRand/Perm/size-64/randbp-8            	  158293	      8404 ns/op	     512 B/op	       1 allocs/op
BenchmarkRand/Perm/size-256/math/rand-8        	   36422	     33602 ns/op	    2048 B/op	       1 allocs/op
BenchmarkRand/Perm/size-256/randbp-8           	   39392	     31592 ns/op	    2048 B/op	       1 allocs/op
BenchmarkRand/Perm/size-512/math/rand-8        	   16131	     66282 ns/op	    4096 B/op	       1 allocs/op
BenchmarkRand/Perm/size-512/randbp-8           	   16870	     66587 ns/op	    4096 B/op	       1 allocs/op
BenchmarkRand/Perm/size-1024/math/rand-8       	   10000	    141570 ns/op	    8192 B/op	       1 allocs/op
BenchmarkRand/Perm/size-1024/randbp-8          	   10000	    135708 ns/op	    8192 B/op	       1 allocs/op
BenchmarkRand/Perm/size-4096/math/rand-8       	    1869	    611661 ns/op	   32769 B/op	       1 allocs/op
BenchmarkRand/Perm/size-4096/randbp-8          	    2143	    527331 ns/op	   32769 B/op	       1 allocs/op
BenchmarkRand/Perm/size-1048576/math/rand-8    	      32	 199437390 ns/op	 8388620 B/op	       1 allocs/op
BenchmarkRand/Perm/size-1048576/randbp-8       	      28	 175333883 ns/op	 8388636 B/op	       1 allocs/op
PASS
ok  	github.com/reddit/baseplate.go/randbp	108.364s
```

**Comment by fishy** [comment]
Used a pool to reduce the overhead from 2us to 1us. New benchmark:

```
$ go test -bench Rand -benchmem
goos: darwin
goarch: amd64
pkg: github.com/reddit/baseplate.go/randbp
BenchmarkRand/Read/size-16/math/rand-8         	 8129785	       137 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-16/crypto/rand-8       	 9775017	       123 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-16/randbp-8            	  950632	      1284 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-64/math/rand-8         	 5527734	       221 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-64/crypto/rand-8       	 5464869	       198 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-64/randbp-8            	  955627	      1301 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-256/math/rand-8        	 4406143	       285 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-256/crypto/rand-8      	 2250775	       556 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-256/randbp-8           	  870771	      1607 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-512/math/rand-8        	 2346324	       514 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-512/crypto/rand-8      	 1000000	      1046 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-512/randbp-8           	  866592	      1557 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-1024/math/rand-8       	 1278798	       961 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-1024/crypto/rand-8     	  622821	      2035 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-1024/randbp-8          	  753301	      1739 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-4096/math/rand-8       	  312086	      3748 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-4096/crypto/rand-8     	  153343	      7961 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-4096/randbp-8          	  488220	      2534 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Read/size-1048576/math/rand-8    	    1278	    860830 ns/op	    6568 B/op	       0 allocs/op
BenchmarkRand/Read/size-1048576/crypto/rand-8  	     873	   1357401 ns/op	    9612 B/op	       0 allocs/op
BenchmarkRand/Read/size-1048576/randbp-8       	    5124	    256605 ns/op	    1645 B/op	       0 allocs/op
BenchmarkRand/Uint64/math/rand-8               	13101903	       107 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Uint64/randbp-8                  	 9246722	       116 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Float64/math/rand-8              	13610248	       113 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Float64/randbp-8                 	12448791	       109 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/NormFloat64/math/rand-8          	 9436459	       124 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/NormFloat64/randbp-8             	 9702868	       127 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/ExpFloat64/math/rand-8           	12500538	       129 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/ExpFloat64/randbp-8              	10463031	       129 ns/op	       0 B/op	       0 allocs/op
BenchmarkRand/Shuffle/size-16/math/rand-8      	  802898	      1896 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-16/randbp-8         	  556371	      2077 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-64/math/rand-8      	  130339	      7946 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-64/randbp-8         	  163762	      7325 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-256/math/rand-8     	   44344	     32573 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-256/randbp-8        	   33708	     31702 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-512/math/rand-8     	   17983	     59325 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-512/randbp-8        	   19387	     62682 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-1024/math/rand-8    	   10000	    126072 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-1024/randbp-8       	    9771	    106986 ns/op	      32 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-4096/math/rand-8    	    2378	    482453 ns/op	      33 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-4096/randbp-8       	    2667	    505488 ns/op	      33 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-1048576/math/rand-8 	      61	 138091625 ns/op	   17233 B/op	       1 allocs/op
BenchmarkRand/Shuffle/size-1048576/randbp-8    	      60	 136763903 ns/op	   17517 B/op	       1 allocs/op
BenchmarkRand/Perm/size-16/math/rand-8         	  717584	      2202 ns/op	     128 B/op	       1 allocs/op
BenchmarkRand/Perm/size-16/randbp-8            	  632422	      1950 ns/op	     128 B/op	       1 allocs/op
BenchmarkRand/Perm/size-64/math/rand-8         	  133977	      8072 ns/op	     512 B/op	       1 allocs/op
BenchmarkRand/Perm/size-64/randbp-8            	  165289	      8742 ns/op	     512 B/op	       1 allocs/op
BenchmarkRand/Perm/size-256/math/rand-8        	   36823	     30805 ns/op	    2048 B/op	       1 allocs/op
BenchmarkRand/Perm/size-256/randbp-8           	   41517	     31250 ns/op	    2048 B/op	       1 allocs/op
BenchmarkRand/Perm/size-512/math/rand-8        	   18561	     69874 ns/op	    4096 B/op	       1 allocs/op
BenchmarkRand/Perm/size-512/randbp-8           	   21290	     66350 ns/op	    4096 B/op	       1 allocs/op
BenchmarkRand/Perm/size-1024/math/rand-8       	   10000	    131028 ns/op	    8192 B/op	       1 allocs/op
BenchmarkRand/Perm/size-1024/randbp-8          	   10000	    140453 ns/op	    8192 B/op	       1 allocs/op
BenchmarkRand/Perm/size-4096/math/rand-8       	    2278	    587424 ns/op	   32768 B/op	       1 allocs/op
BenchmarkRand/Perm/size-4096/randbp-8          	    2359	    560228 ns/op	   32768 B/op	       1 allocs/op
BenchmarkRand/Perm/size-1048576/math/rand-8    	      36	 194900555 ns/op	 8388627 B/op	       1 allocs/op
BenchmarkRand/Perm/size-1048576/randbp-8       	      31	 177157331 ns/op	 8388617 B/op	       1 allocs/op
PASS
ok  	github.com/reddit/baseplate.go/randbp	111.150s
```

**Pull request merged**
