### PR TITLE
thriftclient: Define BaseplateDefaultMiddlewares

### PR DESCRIPTION
**Pull request by fishy**
This makes service code using customized client pool easier to add all
the middlewares recommended by baseplate.

### CODE REVIEW

**Comment by pacejackson** [comment]
We might want to make this a function rather than a mutable global?

**Comment by fishy** [comment]
> We might want to make this a function rather than a mutable global?

I don't feel strongly. In general in go it's more like "if you try to mutate a global variable in another package, you need to know what you are doing and you are at your own risk".

**Comment by fishy** [comment]
For example, if they _really wanted to_, they can mutate that list to add their own middlewares early in their main function, then use the `NewBaseplateClientPool` for several different client pools so they don't need to add those middlewares to those `NewBaseplateClientPool` calls one by one.

**Comment by fishy** [comment]
💇 @pacejackson: I changed it to a function.

**Pull request merged**
