### PR TITLE
Test for data races and fix data race in filewatcher

### PR DESCRIPTION
**Pull request by konradreiche**
I am adding the `-race` flag for tests to test for data races in our code. Looks like we have a data race already but I have problems fixing it. It's because to the data field writes are reads are concurrent.

Given that, I wonder if it makes sense to make the locking more fine granular around writing the data here. Is it necessary to have the lock during the I/O operation? https://github.com/reddit/baseplate.go/blob/master/filewatcher/filewatcher.go#L84-L102

```
==================
WARNING: DATA RACE
Read at 0x00c0000120f0 by goroutine 8:
  github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcher()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:42 +0x50c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous write at 0x00c0000120f0 by goroutine 13:
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:101 +0x190
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:102 +0x377

Goroutine 8 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:50 +0x223

Goroutine 13 (running) created at:
  github.com/reddit/baseplate.go/filewatcher.New()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:166 +0x404
  github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcher()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher_test.go:68 +0x39f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
==================
WARNING: DATA RACE
Read at 0x00c00012a000 by goroutine 8:
  runtime.slicebytetostringtmp()
      /usr/local/go/src/runtime/string.go:142 +0x0
  github.com/reddit/baseplate.go/filewatcher_test.compareBytesData()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher_test.go:32 +0xd1
  github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcher()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher_test.go:92 +0x555
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous write at 0x00c00012a000 by goroutine 13:
  runtime.slicecopy()
      /usr/local/go/src/runtime/slice.go:197 +0x0
  bytes.(*Buffer).grow()
      /usr/local/go/src/bytes/buffer.go:143 +0x22b
  bytes.(*Buffer).ReadFrom()
      /usr/local/go/src/bytes/buffer.go:202 +0x7c
  io/ioutil.readAll()
      /usr/local/go/src/io/ioutil/ioutil.go:36 +0x13e
  github.com/reddit/baseplate.go/filewatcher_test.parser()
      /usr/local/go/src/io/ioutil/ioutil.go:45 +0x4f
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:95 +0x14c
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:102 +0x377

Goroutine 8 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:50 +0x223

Goroutine 13 (running) created at:
  github.com/reddit/baseplate.go/filewatcher.New()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:166 +0x404
  github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcher()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher_test.go:68 +0x39f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
--- FAIL: TestFileWatcher (0.02s)
    testing.go:853: race detected during execution of test
==================
WARNING: DATA RACE
Read at 0x00c0000ee600 by goroutine 18:
  github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcherRename()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:42 +0x50c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous write at 0x00c0000ee600 by goroutine 21:
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:101 +0x190
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:102 +0x377

Goroutine 18 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:50 +0x223

Goroutine 21 (running) created at:
  github.com/reddit/baseplate.go/filewatcher.New()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:166 +0x404
  github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcherRename()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher_test.go:157 +0x39f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
==================
WARNING: DATA RACE
Read at 0x00c000024c00 by goroutine 18:
  runtime.slicebytetostringtmp()
      /usr/local/go/src/runtime/string.go:142 +0x0
  github.com/reddit/baseplate.go/filewatcher_test.compareBytesData()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher_test.go:32 +0xd1
  github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcherRename()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher_test.go:189 +0x555
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous write at 0x00c000024c00 by goroutine 21:
  runtime.slicecopy()
      /usr/local/go/src/runtime/slice.go:197 +0x0
  bytes.(*Buffer).grow()
      /usr/local/go/src/bytes/buffer.go:143 +0x22b
  bytes.(*Buffer).ReadFrom()
      /usr/local/go/src/bytes/buffer.go:202 +0x7c
  io/ioutil.readAll()
      /usr/local/go/src/io/ioutil/ioutil.go:36 +0x13e
  github.com/reddit/baseplate.go/filewatcher_test.parser()
      /usr/local/go/src/io/ioutil/ioutil.go:45 +0x4f
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:95 +0x14c
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:102 +0x377

Goroutine 18 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:50 +0x223

Goroutine 21 (running) created at:
  github.com/reddit/baseplate.go/filewatcher.New()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:166 +0x404
  github.com/reddit/baseplate.go/filewatcher_test.TestFileWatcherRename()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher_test.go:157 +0x39f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
--- FAIL: TestFileWatcherRename (0.02s)
    testing.go:853: race detected during execution of test
FAIL
FAIL	github.com/reddit/baseplate.go/filewatcher	0.147s
?   	github.com/reddit/baseplate.go/log	[no test files]
==================
WARNING: DATA RACE
Write at 0x00c000202630 by goroutine 39:
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:101 +0x190
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:102 +0x377

Previous read at 0x00c000202630 by goroutine 37:
  github.com/reddit/baseplate.go/secrets.(*Store).GetSimpleSecret()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:42 +0x6d
  github.com/reddit/baseplate.go/secrets.TestSecretFileIsUpdated()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store_test.go:248 +0x2bd
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 39 (running) created at:
  github.com/reddit/baseplate.go/filewatcher.New()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:166 +0x404
  github.com/reddit/baseplate.go/secrets.NewStore()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:38 +0x7c
  github.com/reddit/baseplate.go/secrets.TestSecretFileIsUpdated()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store_test.go:244 +0x228
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 37 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:54 +0x223
==================
==================
WARNING: DATA RACE
Read at 0x00c0002fa000 by goroutine 37:
  github.com/reddit/baseplate.go/secrets.(*Store).GetSimpleSecret()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:55 +0xa2
  github.com/reddit/baseplate.go/secrets.TestSecretFileIsUpdated()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store_test.go:271 +0x4bc
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous write at 0x00c0002fa000 by goroutine 39:
  github.com/reddit/baseplate.go/secrets.NewSecrets()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/secrets.go:213 +0x1e5
  github.com/reddit/baseplate.go/secrets.NewStore.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:32 +0x46
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:95 +0x14c
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:102 +0x377

Goroutine 37 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:54 +0x223

Goroutine 39 (running) created at:
  github.com/reddit/baseplate.go/filewatcher.New()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:166 +0x404
  github.com/reddit/baseplate.go/secrets.NewStore()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:38 +0x7c
  github.com/reddit/baseplate.go/secrets.TestSecretFileIsUpdated()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store_test.go:244 +0x228
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
==================
WARNING: DATA RACE
Read at 0x00c0002e2060 by goroutine 37:
  runtime.mapaccess2_faststr()
      /usr/local/go/src/runtime/map_faststr.go:107 +0x0
  github.com/reddit/baseplate.go/secrets.(*Store).GetSimpleSecret()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:55 +0xd9
  github.com/reddit/baseplate.go/secrets.TestSecretFileIsUpdated()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store_test.go:271 +0x4bc
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous write at 0x00c0002e2060 by goroutine 39:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  github.com/reddit/baseplate.go/secrets.NewSecrets()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/secrets.go:225 +0x89f
  github.com/reddit/baseplate.go/secrets.NewStore.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:32 +0x46
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:95 +0x14c
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:102 +0x377

Goroutine 37 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:54 +0x223

Goroutine 39 (running) created at:
  github.com/reddit/baseplate.go/filewatcher.New()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:166 +0x404
  github.com/reddit/baseplate.go/secrets.NewStore()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:38 +0x7c
  github.com/reddit/baseplate.go/secrets.TestSecretFileIsUpdated()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store_test.go:244 +0x228
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
==================
WARNING: DATA RACE
Read at 0x00c0002fc088 by goroutine 37:
  github.com/reddit/baseplate.go/secrets.(*Store).GetSimpleSecret()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:55 +0xf8
  github.com/reddit/baseplate.go/secrets.TestSecretFileIsUpdated()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store_test.go:271 +0x4bc
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Previous write at 0x00c0002fc088 by goroutine 39:
  github.com/reddit/baseplate.go/secrets.NewSecrets()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/secrets.go:225 +0x8b7
  github.com/reddit/baseplate.go/secrets.NewStore.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:32 +0x46
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop.func1()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:95 +0x14c
  github.com/reddit/baseplate.go/filewatcher.(*Result).watcherLoop()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:102 +0x377

Goroutine 37 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:54 +0x223

Goroutine 39 (running) created at:
  github.com/reddit/baseplate.go/filewatcher.New()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/filewatcher/filewatcher.go:166 +0x404
  github.com/reddit/baseplate.go/secrets.NewStore()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store.go:38 +0x7c
  github.com/reddit/baseplate.go/secrets.TestSecretFileIsUpdated()
      /home/konrad-reiche/go/src/github.com/reddit/baseplate.go/secrets/store_test.go:244 +0x228
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
--- FAIL: TestSecretFileIsUpdated (1.00s)
    testing.go:853: race detected during execution of test
FAIL
FAIL	github.com/reddit/baseplate.go/secrets	1.023s
?   	github.com/reddit/baseplate.go/thriftbp	[no test files]
FAIL
```

### CODE REVIEW

**Comment by fishy** [comment]
Oh for that one you just need
```
	r.lock.Lock()
	defer r.lock.Unlock()
```
In the getter here: https://github.com/reddit/baseplate.go/blob/cce7e81a1ad6beb012fdb09c455cfa6ecec70995/filewatcher/filewatcher.go#L42

**Comment by konradreiche** [comment]
> Oh for that one you just need
> 
> ```
> 	r.lock.Lock()
> 	defer r.lock.Unlock()
> ```

[`sync.RWMutex`](https://golang.org/pkg/sync/#RWMutex) has the advantage that it allows simultaneous readers while the `sync.Mutex` only allows on at the same time which can make sense especially when the write lock has a broader scope.

**Comment by fishy** [comment]
> > Oh for that one you just need
> > ```
> > 	r.lock.Lock()
> > 	defer r.lock.Unlock()
> > ```
> 
> [`sync.RWMutex`](https://golang.org/pkg/sync/#RWMutex) has the advantage that it allows simultaneous readers while the `sync.Mutex` only allows on at the same time which can make sense especially when the write lock has a broader scope.

Actually I'll change that into `atomic.Value` instead, which is faster for those use cases.

**Comment by fishy** [comment]
^ Done in: https://github.com/reddit/baseplate.go/pull/12

**Pull request merged**
