### PR TITLE
metricsbp: Buffer udp messages together

### PR DESCRIPTION
**Pull request by fishy**
When using telegraf as the statsd collector, telegraf has a limit of how
many UDP messages can be buffered, and the default go-kit influxstatsd
implementation sends one UDP message per metric on the report interval,
so when we have a lot of metrics, telegraf could be dropping those UDP
messages, thus dropping metrics.

Add a configurable buffer size can help reduce the number of UDP
messages.

Eventually we probably want to upstream this to go-kit.

### CODE REVIEW

**Review by pacejackson — APPROVED** [review]
LGTM, I'm assuming that `st.statsd.WriteTo` just `Writes` each metric to whatever writer you pass it one at a time rather than doing any sort of batching on it's end?

**Comment by fishy** [comment]
> LGTM, I'm assuming that `st.statsd.WriteTo` just `Writes` each metric to whatever writer you pass it one at a time rather than doing any sort of batching on it's end?

Yes exactly. This is the code: https://github.com/go-kit/kit/blob/v0.9.0/metrics/influxstatsd/influxstatsd.go#L142

**Review by konradreiche — APPROVED** [review]
:clap:

**Review by pacejackson — APPROVED** [review]
:doh:

**Pull request merged**
